---
- hosts: dg_masters
  name: Preparing the Primary Database for Standby Database Creation
  sudo: yes
  gather_facts: no
  tasks:
    - name: compose the oracle user creation script
    - name: configure redo transport authentication
    - name: configure the primary database to receive redo data
    - name: set primary database initialization parameters
    - name: enable archiving

- hosts: dg_masters
  name: Creating a Physical Standby Database
  sudo: yes
  gather_facts: no
  tasks:
    - name: Create a Backup Copy of the Primary Database Datafiles
    - name: Create a Control File for the Standby Database
    - name: Create a Parameter File for the Standby Database
    - name: Copy Files from the Primary System to the Standby System


- hosts: dg_physic_slaves
  name: Creating a Physical Standby Database
  sudo: yes
  gather_facts: no
  tasks:
    - name: Set Up the Environment to Support the Standby Database
    - name: Start the Physical Standby Database
    - name: Verify the Physical Standby Database Is Performing Properly

- hosts: dg_logic_slaves
  name: Stop Redo Apply on the Physical Standby Database
  sudo: yes
  gather_facts: no
  tasks:
    - name: Set Up the Environment to Support the Standby Database
    - name: Start the Physical Standby Database
    - name: Verify the Physical Standby Database Is Performing Properly

- hosts: dg_masters
  name: Prepare the Primary Database to Support a Logical Standby Database
  sudo: yes
  gather_facts: no
  tasks:
    - name: Create a Backup Copy of the Primary Database Datafiles
    - name: Create a Control File for the Standby Database
    - name: Create a Parameter File for the Standby Database
    - name: Copy Files from the Primary System to the Standby System

- hosts: dg_logic_slaves
  name: Stop Redo Apply on the Physical Standby Database
  sudo: yes
  gather_facts: no
  tasks:
    - name: Transition to a Logical Standby Database
    - name: Open the Logical Standby Database
    - name: Verify the Logical Standby Database Is Performing Properly
