---
#################### diagnose #######################
- hosts: all
  name: check hosts hareware
  sudo: yes
  tags:
    - diagnose
  tasks:
    - name: check hosts hardware info
      tags: diagnose
      #debug: msg="lsb {{ ansible_lsb }}"
      debug: msg="{{ inventory_hostname }} ,CPU cores {{ ansible_processor_cores }},CPU count {{ ansible_processor_count }}, disk size {{ ansible_devices.sda.size }}, mem mb {{ ansible_memtotal_mb }}, datetime {{ ansible_date_time.iso8601_micro }}, ni {{ ansible_interfaces }}, groups {{ group_names }}" 

- hosts: all
  name: create os users
  sudo: yes
  tags: setup
  tasks:
    - name: create initial groups for the dev user
      group: name=dev state=present

    - name: create dev user
      user:
        name: dev
        group: dev
        home: /home/dev
        shell: /bin/bash
        # gjzspt@!@#
        # mkpasswd --method=SHA-512
        # hashed password for the dev user
        # python -c 'import crypt; print crypt.crypt("gjzspt@!@#", "$1$salt$")'
        password: "$1$salt$Q.mNVqoQheFEuefCuFMJI0"
        append: yes

- hosts: all
  name: setup sudoers
  sudo: yes
  tags: setup
  # tasks:
  #   - name: set setuid for yum
  #     file: 
  #       mode: 6755
  #       path: "/usr/bin/yum"
  vars:
    dev_sudoers:
      - user: "dev"
        user_commands:
          - runas_users:
              - "root"
            commands:
              - "/usr/bin/yum"
            nopasswd: false
  roles:
    - { role: mchlumsky.sudoersd, sudoers_filename: dev, sudoers: "{{ dev_sudoers }}" }

- hosts: local
  name: download oracle 10g
  sudo: yes
  tags: down_files
  tasks:
    - name: download files
      get_url:
        url: "http://download.oracle.com/otn/linux/oracle10g/10201/10201_database_linux_x86_64.cpio.gz"
        dest: /home/helong/he/infra/oracle10g/
        headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
        validate_certs: "no"

- hosts: all
  name: upload installation files
  sudo: yes
  tags: 
    - copy_files
    - install_oracledb
  tasks:
    - name: copy files
      copy:
        src: /home/helong/he/infra/
        dest: /root/dl/

- hosts: all
  name: upload jdk rpm file
  sudo: yes
  tags: 
    - copy_files
    - install_java8
    - install_oracledb
  tasks:
    - name: copy rpm file
      copy:
        src: /home/helong/he/infra/java/jdk-8u91-linux-x64.rpm
        dest: /tmp/jdk-8u91-linux-x64.rpm


#################### install #######################
- hosts: java8
  name: install java8
  sudo: yes
  tags: 
    - install_java8
    - install_oracledb
  vars:
    oracle_jdk_version: 8
    oracle_jdk_update: 91
    oracle_jdk_build_number: b14
  roles:
    - role: medzin.oracle-jdk

- hosts: app
  name: install weblogic server
  #tags: install
  sudo: no
  roles:
    - { role: abessifi.weblogic, sudo: no }

- hosts: zookeeper
  name: install zookeeper
  #tags: install
  sudo: no
  roles:
    - { role: AerisCloud.zookeeper, sudo: no }

- hosts: db
  name: install oracle database server
  tags: 
    - install_oracledb
  sudo: yes
  vars:
    oracle_path: /opt/app  # ORACLE_BASE will be /opt/app/oracle
    oracle_tmp: /tmp/oracle
    oracle_db_name: orcl_dev  # ORACLE_SID will be orcl_dev
    oracle_db_home: oracle  # ORACLE_HOME will be /opt/app/oracle/product/11.2.0/oracle
    oracle_db_user: devuser
    oracle_db_pass: AnAwesomeAndAmazingP4ssw0rd
    oracle_db_syspass: AMor3AwesomeAndAmazingP4ssw0rd
    install_files:
      - linux.x64_11gR2_database_1of2.zip
      - linux.x64_11gR2_database_2of2.zip
  pre_tasks:
    - name: create dir oracle tmp
      command: /bin/mkdir -p {{ oracle_tmp }}
    - name: copy installation files to oracle_tmp 
      command: /bin/cp /root/dl/oralce-rac/{{ item }} {{ oracle_tmp }}/{{ item }}
      with_items: "{{ install_files }}"
  roles:
    - role: ellotheth.oracle

- hosts: nginx
  name: install nginx
  #tags: install
  sudo: yes
  roles:
    - role: geerlingguy.nginx

- hosts: cache
  name: install memecached
  tags: install
  sudo: yes
  roles:
    - role: cchurch.memcached