---
#################### diagnose #######################
- hosts: all
  name: check hosts hareware
  sudo: yes
  tags:
    - diagnose
  tasks:
    - name: check hosts hardware info
      tags: diagnose
      #debug: msg="lsb {{ ansible_lsb }}"
      debug: msg="{{ inventory_hostname }} ,CPU cores {{ ansible_processor_cores }},CPU count {{ ansible_processor_count }}, disk size {{ ansible_devices.sda.size }}, mem mb {{ ansible_memtotal_mb }}, datetime {{ ansible_date_time.iso8601_micro }}, ni {{ ansible_interfaces }}, groups {{ group_names }}" 

#################### setup #######################
- hosts: all
  name: create os users
  sudo: yes
  tags: 
    - setup
    - setup_user
  tasks:
    - name: create initial groups for the dev user
      group: name=dev state=present

    - name: create dev user
      user:
        name: dev
        group: dev
        home: /home/dev
        shell: /bin/bash
        # gjzspt@!@#
        # mkpasswd --method=SHA-512
        # hashed password for the dev user
        # python -c 'import crypt; print crypt.crypt("gjzspt@!@#", "$1$salt$")'
        password: "$1$salt$Q.mNVqoQheFEuefCuFMJI0"
        append: yes

- hosts: all
  name: setup sudoers
  sudo: yes
  tags: 
    - setup
    - setup_user
  vars:
    dev_sudoers:
      - user: "dev"
        user_commands:
          - runas_users:
              - "root"
            commands:
              - "/usr/bin/yum"
            nopasswd: false
  roles:
    - { role: mchlumsky.sudoersd, sudoers_filename: dev, sudoers: "{{ dev_sudoers }}" }


- hosts: all
  name: auto start sshd
  sudo: yes
  tags:
    - setup
    - setup_autostart_sshd
  tasks:
    - service: name=sshd enabled=yes

- hosts: all
  name: set hostname
  sudo: yes
  tags:
    - setup
    - setup_set_hostname
  tasks:
    - hostname: name={{ hostname }}

- hosts: all
  name: turn off firewall
  sudo: yes
  tags:
    - setup
    - setup_off_iptables
  tasks:
    - service: name=iptables state=stopped enabled=yes

#################### files #######################

- hosts: local
  name: download oracle 10g
  sudo: yes
  tags: 
    - down_files
  tasks:
    - name: download files
      get_url:
        url: "http://download.oracle.com/otn/linux/oracle10g/10201/10201_database_linux_x86_64.cpio.gz"
        dest: /home/helong/he/infra/oracle10g/
        headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
        validate_certs: "no"

- hosts: all
  name: upload installation files
  sudo: yes
  tags: 
    - copy_files
    - install_oracledb
  tasks:
    - name: copy files
      copy:
        src: /home/helong/he/infra/
        dest: /root/dl/

- hosts: all
  name: upload jdk rpm file
  sudo: yes
  tags: 
    - copy_files
    - install_java8
    - install_oracledb
  tasks:
    - name: copy rpm file
      copy:
        src: /home/helong/he/infra/java/jdk-8u91-linux-x64.rpm
        dest: /tmp/jdk-8u91-linux-x64.rpm


#################### install #######################
- hosts: java8
  name: install java8
  sudo: yes
  tags: 
    - install_java8
    - install_oracledb
  vars:
    oracle_jdk_version: 8
    oracle_jdk_update: 91
    oracle_jdk_build_number: b14
  roles:
    - role: medzin.oracle-jdk

- hosts: app
  name: install weblogic server
  #tags: install
  sudo: no
  roles:
    - { role: abessifi.weblogic, sudo: no }

- hosts: zookeeper
  name: install zookeeper
  #tags: install
  sudo: no
  roles:
    - { role: AerisCloud.zookeeper, sudo: no }

- hosts: db
  name: install oracle database server
  tags: 
    - install_oracledb
  sudo: yes
  vars:
    oracle_path: /opt/app  # ORACLE_BASE will be /opt/app/oracle
    oracle_tmp: /tmp/oracle
    oracle_db_name: gjzsptdev  # ORACLE_SID will be orcl_dev
    oracle_db_home: oracle  # ORACLE_HOME will be /opt/app/oracle/product/11.2.0/oracle
    oracle_db_user: dev
    # alphanum or _ or $ or #
    oracle_db_pass: "123456"
    oracle_db_syspass: "Oe123qwe###"
    install_files:
      - linux.x64_11gR2_database_1of2.zip
      - linux.x64_11gR2_database_2of2.zip
  pre_tasks:
    - name: create dir oracle tmp
      file:
        path: "{{ oracle_tmp }}"
        state: directory
    - name: copy installation files to oracle_tmp 
      command: /bin/cp /root/dl/oralce-rac/{{ item }} {{ oracle_tmp }}/{{ item }}
      with_items: "{{ install_files }}"
  roles:
    - role: ellotheth.oracle

#sqlplus sys/Oe123qwe###@gjzsptdev as sysdba
#sqlplus64 sys/Oe123qwe###@//192.168.122.109:1521/gjzsptdev as sysdba

- hosts: nginx
  name: install nginx
  #tags: install
  sudo: yes
  roles:
    - role: geerlingguy.nginx

- hosts: cache
  name: install memecached
  tags: install
  sudo: yes
  roles:
    - role: cchurch.memcached