---
- hosts: all
  sudo: no
  tasks:
    - name: check hosts hardware info
      tags: diagnose
      #debug: msg="lsb {{ ansible_lsb }}"
      debug: msg="System {{ inventory_hostname }}, groups {{ group_names }} ,CPU count {{ ansible_processor_count }}, disk size {{ ansible_devices.sda.size }}, mem mb {{ ansible_memtotal_mb }}, datetime {{ ansible_date_time.iso8601_micro }}, ni {{ ansible_interfaces }} " 
