---
- hosts: '{{ target }}'
#- hosts: all
  sudo: no
  tasks:
    - name: check hosts hardware info
      tags: diagnose
      #debug: msg="lsb {{ ansible_lsb }}"
      debug: msg="{{ inventory_hostname }} ,CPU cores {{ ansible_processor_cores }},CPU count {{ ansible_processor_count }}, disk size {{ ansible_devices.sda.size }}, mem mb {{ ansible_memtotal_mb }}, datetime {{ ansible_date_time.iso8601_micro }}, ni {{ ansible_interfaces }}, groups {{ group_names }}" 

- hosts: '{{ target }}'
#- hosts: all
  sudo: no
  tags: setup
  tasks:
    - name: create initial groups for the dev user
      group: name=dev state=present

    - name: create dev user
      user:
        name: dev
        group: dev
        home: /home/dev
        shell: /bin/bash
        # gjzspt@!@#
        # mkpasswd --method=SHA-512
        # hashed password for the dev user
        # python -c 'import crypt; print crypt.crypt("gjzspt@!@#", "$1$salt$")'
        password: "$1$salt$Q.mNVqoQheFEuefCuFMJI0"
        append: yes

- hosts: '{{ target }}'
#- hosts: all
  sudo: no
  tags: setup
  tasks:
    - name: set sticky bit for yum
      file: 
        mode: 6755
        path: "/usr/bin/yum"
  vars:
    dev_sudoers:
      - user: "dev"
        user_commands:
          - runas_users:
              - "root"
            commands:
              - "/usr/bin/yum"
            nopasswd: false
  roles:
    - { role: mchlumsky.sudoersd, sudoers_filename: dev, sudoers: "{{ dev_sudoers }}" }

- hosts: java8
  sudo: yes
  #tags: install
  vars:
    oracle_jdk_version: 8
    oracle_jdk_update: 91
    oracle_jdk_build_number: b14
  roles:
    - role: medzin.oracle-jdk

- hosts: app
  #tags: install
  sudo: no
  roles:
    - { role: abessifi.weblogic, sudo: no }

- hosts: zookeeper
  #tags: install
  sudo: no
  roles:
    - { role: AerisCloud.zookeeper, sudo: no }

- hosts: db
  #tags: install
  sudo: yes
  vars:
    oracle_path: /opt/app  # ORACLE_BASE will be /opt/app/oracle
    oracle_install_file1: /home/helong/he/infra/linux.x64_11gR2_database_1of2.zip
    oracle_install_file2: /linux.x64_11gR2_database_2of2.zip
    oracle_tmp: /tmp/oracle
    oracle_db_name: orcl_dev  # ORACLE_SID will be orcl_dev
    oracle_db_home: oracle  # ORACLE_HOME will be /opt/app/oracle/product/11.2.0/oracle
    oracle_db_user: devuser
    oracle_db_pass: AnAwesomeAndAmazingP4ssw0rd
    oracle_db_syspass: AMor3AwesomeAndAmazingP4ssw0rd
  tasks:
    - name: upload installation files 
      copy:
        src: "{{oracle_install_file1}}"
        dest: "{{oracle_tmp}}"
    - name: upload installation files 
      copy:
        src: "{{oracle_install_file2}}"
        dest: "{{oracle_tmp}}"
  roles:
    - role: ellotheth.oracle

- hosts: nginx
  #tags: install
  sudo: yes
  roles:
    - role: geerlingguy.nginx

- hosts: cache
  tags: install
  sudo: yes
  roles:
    - role: cchurch.memcached