- name: Install Cloustack KVM agent
  hosts: cloudstack_agents
  vars:
    cloudstack_repo: "http://cloudstack.apt-get.eu/centos"
    cloudstack_ver: "4.4"
    cloudstack_agent_tuned: true
  roles:
    - cloudstack-common
    - cloudstack-agent
