#!/bin/bash
set -x

WRK_DIR=/home/hadoop/i
ZOOKEEPER_CONF_DIR=$ZOOKEEPER_HOME/conf
ZOOKEEPER_CONF_BKUP_DIR=$WRK_DIR/bak-zookeeper-conf
BAK_SUFFIX=ori

mv $ZOOKEEPER_CONF_DIR/zoo.cfg $ZOOKEEPER_CONF_DIR/zoo.$BAK_SUFFIX.cfg 
cp $ZOOKEEPER_CONF_BKUP_DIR/* $ZOOKEEPER_CONF_DIR
