/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sharpx_jni_ubuntu_Test2Intf */

#ifndef _Included_sharpx_jni_ubuntu_Test2Intf
#define _Included_sharpx_jni_ubuntu_Test2Intf
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
