/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sharpx_jni_ubuntu_Main */

#ifndef _Included_sharpx_jni_ubuntu_Main
#define _Included_sharpx_jni_ubuntu_Main
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
