/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sharpx_jni_ubuntu_Test2Impl1 */

#ifndef _Included_sharpx_jni_ubuntu_Test2Impl1
#define _Included_sharpx_jni_ubuntu_Test2Impl1
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
