/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sharpx_jni_ubuntu_Test2JniImpl */

#ifndef _Included_sharpx_jni_ubuntu_Test2JniImpl
#define _Included_sharpx_jni_ubuntu_Test2JniImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sharpx_jni_ubuntu_Test2JniImpl
 * Method:    staticHaha
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sharpx_jni_ubuntu_Test2JniImpl_staticHaha
  (JNIEnv *, jclass);

/*
 * Class:     sharpx_jni_ubuntu_Test2JniImpl
 * Method:    haha
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sharpx_jni_ubuntu_Test2JniImpl_haha
  (JNIEnv *, jobject);

/*
 * Class:     sharpx_jni_ubuntu_Test2JniImpl
 * Method:    abc
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sharpx_jni_ubuntu_Test2JniImpl_abc
  (JNIEnv *, jobject, jint);

/*
 * Class:     sharpx_jni_ubuntu_Test2JniImpl
 * Method:    callBackJ
 * Signature: (Lsharpx/jni/ubuntu/Test2CallBackIntf;)V
 */
JNIEXPORT void JNICALL Java_sharpx_jni_ubuntu_Test2JniImpl_callBackJ
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
