---

- hosts: vm
  sudo: yes
  roles:
    - { role: he.tomcat-req, tags: 'vm' }
    - { role: stevenvandervalk.tomcat, tags: 'tomcat', sudo: yes }
    - { role: Rackspace_Automation.mysql, tags: 'mysql', sudo: yes, mysql_root_password: '123qwe!@#' }
    - { role: geerlingguy.nginx, tags: 'nginx', sudo: yes }

- hosts: logstash-server
  sudo: yes
  roles:
    # - { role: geerlingguy.redis, tags: 'logstash', sudo: yes }
    - { role: geerlingguy.logstash, tags: 'logstash', sudo: yes }
    - { role: geerlingguy.elasticsearch, tags: 'logstash', sudo: yes }

    - { role: geerlingguy.nginx, tags: 'kibana', sudo: yes }
    - { role: geerlingguy.repo-epel, tags: 'kibana', sudo: yes }
    - { role: geerlingguy.kibana, tags: 'kibana', sudo: yes, kibana_server_name: "{{ logweb_host }}",
      kibana_username: "long.he", kibana_password: "123qwe!@#" }
  tasks:
    # setup elasticsearch
    - name: add cors.enabled in /etc/elasticsearch/elasticsearch.yml
      tags: logstash
      lineinfile: 
        dest: /etc/elasticsearch/elasticsearch.yml
        line: "http.cors.enabled: true"
    - name: add cors.allow-origion in /etc/elasticsearch/elasticsearch.yml
      tags: logstash
      lineinfile: 
        dest: /etc/elasticsearch/elasticsearch.yml
        line: "http.cors.allow-origion: http://{{ logweb_host }}:80"

    # setup kibana users
#    - name: install elasticsearch plugins
#      tags: logstash-users
#      shell: test -d plugins/license || bin/plugin -i elasticsearch/license/1.0.0 -Des.path.conf=/etc/elasticsearch
#        && test -d plugins/shield || bin/plugin -i elasticsearch/shield/1.3.3 -Des.path.conf=/etc/elasticsearch
#      args:
#        executable: /bin/bash
#        chdir: /usr/share/elasticsearch
#    - name: add esusers users
#      tags: logstash-users
#      shell: bin/shield/esusers useradd long.he -p '123qwe!@#' -r logstash,kibana3
#        && bin/shield/esusers useradd logstash-indexer -p '12345678' -r admin
#      args:
#        executable: /bin/bash
#        chdir: /usr/share/elasticsearch

#- hosts: localhost
#  roles:
#    - { role: stevenvandervalk.tomcat, tags: 'tomcat', sudo: yes }

- hosts: logstash-agent
  sudo: yes
  vars:
    logstash_forwarder_logstash_server: logstash.tcredit.com
  tasks:
    - name: remove logstash.example.com in /etc/hosts
      tags: logstash
      lineinfile:
        dest: /etc/hosts
        regexp: '.*logstash\.tcredit\.com.*'
        state: absent
    - name: add logstash.tcredit.com in /etc/hosts
      tags: logstash
      lineinfile:
        dest: /etc/hosts
        line: "{{ logstash_server_ip }} logstash.tcredit.com"
  roles:
    - { role: geerlingguy.logstash-forwarder, tags: 'logstash' }
