export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/local/sqlshell/bin:$PATH"

PROMPT='%m:%.$ '
alias emacs='emacs -nw'
alias ls='ls --color=auto'
HISTFILE="$HOME/.zsh_history"
HISTSIZE=SAVEHIST=1000
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt EXTENDED_HISTORY
