#include "jpVoc.h"
// Main entry point for this example
//

short parseJpVoc(const char* str,VocInfo vi){
	pANTLR3_INPUT_STREAM input;
	pJpVocabularyLexer lxr;
	pANTLR3_COMMON_TOKEN_STREAM tstream;
	pJpVocabularyParser psr;

	ANTLR3_FPRINTF(stdout,"parseJpVoc:%s\n",str);
	input = antlr3StringStreamNew((pANTLR3_UINT8)str, ANTLR3_ENC_UTF8,
			strlen(str),(pANTLR3_UINT8)"jpVocabu");

	initParser(&input,&lxr,&tstream,&psr);
	psr->vocabulary(psr,vi.pronun,
			vi.writing,vi.partOfSpeech,vi.expl);

	ANTLR3_FPRINTF(stdout,"parseJpVoc:pronun:%s\twriting:%s\tpartOfSpeech:%s\texpl:%s\n",
			vi.pronun,vi.writing,vi.partOfSpeech,vi.expl);
	cleanParser(&input,&lxr,&tstream,&psr);
	return 0;
}

void initVocInfo(VocInfo* vi){
	vi->pronun = calloc(200,1);
	vi->writing = calloc(200,1);
	vi->partOfSpeech = calloc(200,1);
	vi->expl = calloc(200,1);
}

void clearVocInfo(VocInfo* vi){
    free(vi->pronun);
    free(vi->writing);
    free(vi->partOfSpeech);
    free(vi->expl);
}

/*
VocInfo parseJpVoc2(const char* str){
	pANTLR3_INPUT_STREAM input;
	pJpVocabularyLexer lxr;
	pANTLR3_COMMON_TOKEN_STREAM tstream;
	pJpVocabularyParser psr;

	ANTLR3_FPRINTF(stdout,"parseJpVoc:%s\n",str);
	input = antlr3StringStreamNew((pANTLR3_UINT8)str, ANTLR3_ENC_UTF8,
			strlen(str),(pANTLR3_UINT8)"jpVocabu");

	initParser(&input,&lxr,&tstream,&psr);
	JpVocabularyParser_vocabulary_return ret = psr->vocabulary(psr,NULL,NULL,NULL,NULL);
	VocInfo vi;
	char* t=malloc(100);
	vi.pronun = strcpy(t, ret.pronun);
	t=malloc(100);
	vi.writing = strcpy(t,ret.writing);
	t=malloc(100);
	vi.partOfSpeech = strcpy(t,ret.partOfSpeech);
	t=malloc(100);
	vi.expl = strcpy(t,ret.expl);
	ANTLR3_FPRINTF(stdout,"parseJpVoc:pronun:%s\twriting:%s\tpartOfSpeech:%s\texpl:%s\n",
			vi.pronun,vi.writing,vi.partOfSpeech,vi.expl);
	cleanParser(&input,&lxr,&tstream,&psr);
	return vi;
}
*/

void initParser(pANTLR3_INPUT_STREAM* input,pJpVocabularyLexer* lxr,
		pANTLR3_COMMON_TOKEN_STREAM* tstream,
		pJpVocabularyParser* psr){
	*lxr = JpVocabularyLexerNew(*input); // CLexerNew is generated by ANTLR

	if (*lxr == NULL) {
		ANTLR3_FPRINTF(stderr,
				"Unable to create the lexer due to malloc() failure1\n");
		exit(ANTLR3_ERR_NOMEM);
	}

	*tstream = antlr3CommonTokenStreamSourceNew(ANTLR3_SIZE_HINT,
			TOKENSOURCE((*lxr)));

	if (*tstream == NULL) {
		ANTLR3_FPRINTF(stderr,
				"Out of memory trying to allocate token stream\n");
		exit(ANTLR3_ERR_NOMEM);
	}

	*psr = JpVocabularyParserNew(*tstream); // CParserNew is generated by ANTLR3

	if (*psr == NULL) {
		ANTLR3_FPRINTF(stderr, "Out of memory trying to allocate parser\n");
		exit(ANTLR3_ERR_NOMEM);
	}
}

void cleanParser(pANTLR3_INPUT_STREAM* input,pJpVocabularyLexer* lxr,
		pANTLR3_COMMON_TOKEN_STREAM* tstream,
		pJpVocabularyParser* psr){
	(*psr)->free(*psr);
	*psr = NULL;
	(*tstream)->free(*tstream);
	*tstream = NULL;
	(*lxr)->free(*lxr);
	*lxr = NULL;
	(*input)->close(*input);
	*input = NULL;
}
