---
- name: stop tomcat
  service: name=tomcat state=stopped

- name: start tomcat
  service: name=tomcat state=started

- name: restart tomcat 
  service: name=tomcat state=restarted

- name: restart iptables
  service: name=iptables state=restarted
