/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sharp_vocreader_jni_VocabularySupport */

#ifndef _Included_org_sharp_vocreader_jni_VocabularySupport
#define _Included_org_sharp_vocreader_jni_VocabularySupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sharp_vocreader_jni_VocabularySupport
 * Method:    parseMp3Name
 * Signature: (Ljava/lang/String;Lorg/sharp/vocreader/jni/beans/Vocabulary;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sharp_vocreader_jni_VocabularySupport_parseMp3Name
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
