# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    config.vm.define "svr1" do |svr|
      svr.vm.box = "CentOS-6.5-x86_64"
      svr.vm.network "private_network", ip: "192.168.100.89"
      svr.vm.provider "virtualbox" do |vb|
        vb.name = "CentOS-89"
      end
    end

    config.vm.define "svr2" do |svr|
      svr.vm.box = "CentOS-6.5-x86_64"
      svr.vm.network "private_network", ip: "192.168.100.88"
      svr.vm.provider "virtualbox" do |vb|
        vb.name = "CentOS-88"
      end
    end

end
