
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __sharpx_jni_Test__
#define __sharpx_jni_Test__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace sharpx
  {
    namespace jni
    {
        class Test;
    }
  }
}

class sharpx::jni::Test : public ::java::lang::Object
{

public:
  Test();
  virtual ::java::lang::String * testJniCpp(jint);
  virtual void callBack(::java::lang::String *);
  static ::java::lang::Class class$;
};

#endif // __sharpx_jni_Test__
