---
#################### diagnose #######################
- hosts: all
  name: check hosts info
  sudo: no
  tags:
    - diagnose
  tasks:
    - name: check hosts hardware info
      tags: diagnose
      #debug: msg="lsb {{ ansible_lsb }}"
      debug: msg="{{ inventory_hostname }} ,CPU cores {{ ansible_processor_cores }},CPU count {{ ansible_processor_count }}, disk size {{ ansible_devices.sda.size }}, mem mb {{ ansible_memtotal_mb }}, datetime {{ ansible_date_time.iso8601_micro }}, ni {{ ansible_interfaces }}, groups {{ group_names }}" 
    - name: check hosts software info
      tags: diagnose
      #debug: msg="lsb {{ ansible_lsb }}"
      debug: msg="{{ ansible_distribution_release }}" 

- hosts: localhost
  name: install mesos
  sudo: yes
  tags:
    - install_mesos
    - install
  vars:
    #- mesos_version: 2.8.2
  roles:
    #- andrewrothstein.mesosphere-mesos
    #- andrewrothstein.mesosphere-mesosmaster
    - azavea.mesos